'use client';

import React, { useMemo, useRef, useState } from 'react';
import * as LucideIcons from 'lucide-react';
import { ACTION_CATALOG, AutomationCatalogItem, TRIGGER_CATALOG } from '@/lib/automation-catalog';

type WorkflowCanvasProps = {
  workflow: any;
  saving: boolean;
  onChangeTrigger: (item: AutomationCatalogItem) => Promise<void>;
  onRemoveTrigger: (index: number) => Promise<void>;
  onChangeSteps: (steps: any[]) => Promise<void>;
};

const iconFor = (name: string) => {
  const icons = LucideIcons as unknown as Record<string, React.ComponentType<{ className?: string }>>;
  return icons[name] || LucideIcons.Zap;
};

const colorClasses: Record<string, string> = {
  amber: 'border-amber-400/25 bg-amber-400/10 text-amber-300', blue: 'border-blue-400/25 bg-blue-400/10 text-blue-300',
  cyan: 'border-cyan-400/25 bg-cyan-400/10 text-cyan-300', emerald: 'border-emerald-400/25 bg-emerald-400/10 text-emerald-300',
  fuchsia: 'border-fuchsia-400/25 bg-fuchsia-400/10 text-fuchsia-300', green: 'border-green-400/25 bg-green-400/10 text-green-300',
  indigo: 'border-indigo-400/25 bg-indigo-400/10 text-indigo-300', orange: 'border-orange-400/25 bg-orange-400/10 text-orange-300',
  purple: 'border-purple-400/25 bg-purple-400/10 text-purple-300', red: 'border-red-400/25 bg-red-400/10 text-red-300',
  rose: 'border-rose-400/25 bg-rose-400/10 text-rose-300', slate: 'border-slate-400/25 bg-slate-400/10 text-slate-300',
  teal: 'border-teal-400/25 bg-teal-400/10 text-teal-300', yellow: 'border-yellow-400/25 bg-yellow-400/10 text-yellow-300',
};

function Catalog({ tab, onAdd, onTrigger }: { tab: 'triggers' | 'actions'; onAdd: (item: AutomationCatalogItem) => void; onTrigger: (item: AutomationCatalogItem) => void }) {
  const [query, setQuery] = useState('');
  const scrollAreaRef = useRef<HTMLDivElement>(null);
  const groups = tab === 'triggers' ? TRIGGER_CATALOG : ACTION_CATALOG;
  const filtered = useMemo(() => groups.map((group) => ({ ...group, items: group.items.filter((item) => `${item.label} ${item.description}`.toLowerCase().includes(query.toLowerCase())) })).filter((group) => group.items.length), [groups, query]);
  const scrollCatalog = (direction: number) => scrollAreaRef.current?.scrollBy({ top: direction * 320, behavior: 'smooth' });
  return <div className="flex min-h-0 flex-1 flex-col bg-surface-card">
    <div className="border-b border-border p-3"><div className="relative"><LucideIcons.Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${tab}...`} className="w-full rounded-lg border border-border bg-surface py-2 pl-9 pr-3 text-xs text-white outline-none focus:border-primary-500" /></div></div>
    <button type="button" onClick={() => scrollCatalog(-1)} aria-label={`Scroll ${tab} up`} className="mx-3 mt-2 flex items-center justify-center rounded-lg border border-border bg-surface py-1.5 text-slate-500 hover:border-primary-500/40 hover:text-primary-300"><LucideIcons.ChevronUp className="h-4 w-4" /></button>
    <div ref={scrollAreaRef} className="min-h-0 flex-1 space-y-4 overflow-y-scroll p-3 [scrollbar-color:rgb(71_85_105)_transparent] [scrollbar-width:thin]">{filtered.map((group) => <section key={group.id}><h3 className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">{group.label}</h3><div className="space-y-1">{group.items.map((item) => { const Icon = iconFor(item.icon); return <button key={item.id} draggable={tab === 'actions'} onDragStart={(event) => { event.dataTransfer.setData('automation/catalog-item', JSON.stringify(item)); event.dataTransfer.effectAllowed = 'copy'; }} onClick={() => tab === 'triggers' ? onTrigger(item) : onAdd(item)} className="group flex w-full items-center gap-2.5 rounded-lg border border-transparent p-2 text-left hover:border-border hover:bg-surface-elevated"><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border ${colorClasses[item.color] || colorClasses.slate}`}><Icon className="h-3.5 w-3.5" /></span><span className="min-w-0"><span className="block truncate text-[11px] font-semibold text-slate-200">{item.label}</span><span className="block truncate text-[9px] text-slate-500">{item.description}</span></span><LucideIcons.GripVertical className="ml-auto h-3.5 w-3.5 text-slate-700 group-hover:text-slate-500" /></button>; })}</div></section>)}</div>
    <button type="button" onClick={() => scrollCatalog(1)} aria-label={`Scroll ${tab} down`} className="mx-3 mb-3 flex items-center justify-center rounded-lg border border-border bg-surface py-1.5 text-slate-500 hover:border-primary-500/40 hover:text-primary-300"><LucideIcons.ChevronDown className="h-4 w-4" /></button>
  </div>;
}

export function WorkflowCanvas({ workflow, saving, onChangeTrigger, onRemoveTrigger, onChangeSteps }: WorkflowCanvasProps) {
  const [tab, setTab] = useState<'triggers' | 'actions'>('triggers');
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const [dragIndex, setDragIndex] = useState<number | null>(null);
  const [zoom, setZoom] = useState(1);
  const [builderTab, setBuilderTab] = useState<'builder' | 'settings' | 'enrollment' | 'logs'>('builder');
  const canvasRef = useRef<HTMLDivElement>(null);
  const steps = workflow.steps || [];

  const makeStep = (item: AutomationCatalogItem, order: number) => ({ name: item.label, actionType: item.runtimeType, order, config: { ...(item.config || {}), ...(item.runtimeType === 'WEBHOOK' ? { url: '', method: 'POST' } : {}) } });
  const normalize = (items: any[]) => items.map((step, order) => ({ ...step, order }));
  const insertItem = (item: AutomationCatalogItem, at = steps.length) => void onChangeSteps(normalize([...steps.slice(0, at), makeStep(item, at), ...steps.slice(at)]));
  const reorder = (from: number, to: number) => { const next = [...steps]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setDragIndex(null); void onChangeSteps(normalize(next)); };
  const updateSelected = (patch: Record<string, unknown>) => { if (selectedIndex === null) return; const next = steps.map((step: any, index: number) => index === selectedIndex ? { ...step, ...patch } : step); void onChangeSteps(normalize(next)); };
  const triggerItem = TRIGGER_CATALOG.flatMap((group) => group.items).find((item) => item.id === workflow.trigger?.type || item.id === workflow.trigger?.config?.eventType);
  const TriggerIcon = iconFor(triggerItem?.icon || 'Zap');
  const additionalTriggers = Array.isArray(workflow.trigger?.config?.additionalTriggers) ? workflow.trigger.config.additionalTriggers : [];
  const displayedTriggers = [{ id: workflow.trigger?.config?.eventType || workflow.trigger?.type, type: workflow.trigger?.type, config: workflow.trigger?.config }, ...additionalTriggers];

  return <div ref={canvasRef} className="grid h-[calc(100vh-205px)] min-h-[620px] grid-cols-[250px_minmax(520px,1fr)_280px] grid-rows-[52px_minmax(0,1fr)] overflow-hidden rounded-2xl border border-border bg-[#0a0d14]">
    <nav className="col-span-3 flex items-center justify-between border-b border-border bg-surface-card px-4"><div className="flex items-center gap-1">{(['builder', 'settings', 'enrollment', 'logs'] as const).map((item) => <button key={item} onClick={() => setBuilderTab(item)} className={`relative px-3 py-4 text-[10px] font-semibold capitalize ${builderTab === item ? 'text-primary-300 after:absolute after:inset-x-2 after:bottom-0 after:h-0.5 after:bg-primary-500' : 'text-slate-500 hover:text-slate-300'}`}>{item === 'enrollment' ? 'Enrollment history' : item === 'logs' ? 'Execution logs' : item}</button>)}</div><div className="flex items-center gap-2"><span className="flex items-center gap-1.5 text-[9px] text-slate-500"><span className={`h-1.5 w-1.5 rounded-full ${saving ? 'bg-amber-400' : 'bg-emerald-400'}`} />{saving ? 'Saving changes' : 'All changes saved'}</span><button onClick={() => setZoom(1)} className="rounded-lg border border-border px-2 py-1.5 text-[9px] text-slate-400">Reset view</button></div></nav>
    <aside className="flex min-h-0 flex-col border-r border-border"><div className="grid shrink-0 grid-cols-2 border-b border-border p-2"><button onClick={() => setTab('triggers')} className={`rounded-lg py-2 text-[11px] font-semibold ${tab === 'triggers' ? 'bg-primary-600 text-white' : 'text-slate-500'}`}>Triggers</button><button onClick={() => setTab('actions')} className={`rounded-lg py-2 text-[11px] font-semibold ${tab === 'actions' ? 'bg-primary-600 text-white' : 'text-slate-500'}`}>Actions & Apps</button></div><Catalog tab={tab} onAdd={insertItem} onTrigger={(item) => void onChangeTrigger(item)} /></aside>
    <main className="relative overflow-auto bg-[radial-gradient(circle_at_1px_1px,rgba(148,163,184,0.13)_1px,transparent_0)] [background-size:22px_22px]">
      {saving && <div className="absolute right-4 top-4 z-20 flex items-center gap-2 rounded-full border border-border bg-surface/90 px-3 py-1.5 text-[10px] text-slate-400"><LucideIcons.Loader2 className="h-3 w-3 animate-spin" />Saving</div>}
      <div className="absolute left-3 top-3 z-20 flex flex-col overflow-hidden rounded-lg border border-border bg-surface shadow-xl">{[{ icon: LucideIcons.MessageSquare, label: 'Notes' }, { icon: LucideIcons.CheckCircle2, label: 'Validation' }, { icon: LucideIcons.History, label: 'History' }, { icon: LucideIcons.FileText, label: 'Documents' }, { icon: LucideIcons.Search, label: 'Find node' }, { icon: LucideIcons.Sparkles, label: 'AI assistant' }].map(({ icon: Icon, label }) => <button key={label} title={label} className="border-b border-border p-2.5 text-slate-500 last:border-0 hover:bg-surface-elevated hover:text-primary-300"><Icon className="h-3.5 w-3.5" /></button>)}</div>
      <div className="absolute bottom-4 left-4 z-20 flex flex-col overflow-hidden rounded-lg border border-border bg-surface shadow-xl"><button title="Pan canvas" className="border-b border-border p-2 text-slate-400 hover:bg-surface-elevated"><LucideIcons.Hand className="h-3.5 w-3.5" /></button><button title="Zoom in" onClick={() => setZoom(Math.min(1.5, zoom + .1))} className="border-b border-border p-2 text-slate-400 hover:bg-surface-elevated"><LucideIcons.Plus className="h-3.5 w-3.5" /></button><button title="Reset zoom" onClick={() => setZoom(1)} className="border-b border-border px-2 py-2 text-[9px] text-slate-400 hover:bg-surface-elevated">{Math.round(zoom * 100)}%</button><button title="Zoom out" onClick={() => setZoom(Math.max(.5, zoom - .1))} className="border-b border-border p-2 text-slate-400 hover:bg-surface-elevated"><LucideIcons.Minus className="h-3.5 w-3.5" /></button><button title="Fit workflow" onClick={() => setZoom(.8)} className="border-b border-border p-2 text-slate-400 hover:bg-surface-elevated"><LucideIcons.Scan className="h-3.5 w-3.5" /></button><button title="Fullscreen" onClick={() => canvasRef.current?.requestFullscreen()} className="p-2 text-slate-400 hover:bg-surface-elevated"><LucideIcons.Maximize2 className="h-3.5 w-3.5" /></button></div>
      <div className="mx-auto flex min-h-full w-[1200px] origin-top flex-col items-center px-20 py-12 transition-transform" style={{ transform: `scale(${zoom})` }}>
        <div className="flex max-w-[1050px] flex-wrap items-stretch justify-center gap-3">{displayedTriggers.map((entry: any, index: number) => { const item = TRIGGER_CATALOG.flatMap((group) => group.items).find((catalogTrigger) => catalogTrigger.id === entry.id || catalogTrigger.id === entry.config?.eventType || catalogTrigger.runtimeType === entry.type); const Icon = iconFor(item?.icon || 'Zap'); return <article key={`${entry.id}-${index}`} className="group relative w-52 rounded-xl border border-emerald-400/35 bg-surface-card p-3 shadow-[0_12px_40px_rgba(0,0,0,.35)]"><div className="flex items-start gap-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-emerald-400/25 bg-emerald-400/10 text-emerald-300"><Icon className="h-4 w-4" /></span><div className="min-w-0"><div className="text-[8px] font-bold uppercase tracking-wider text-emerald-400">Trigger {index + 1}</div><div className="mt-1 truncate text-[10px] font-bold text-white">{item?.label || entry.type?.replaceAll('_', ' ')}</div><div className="mt-1 truncate text-[8px] text-slate-500">Starts this workflow</div></div></div>{index > 0 && <button onClick={() => void onRemoveTrigger(index)} title="Remove trigger" className="absolute right-1.5 top-1.5 hidden rounded p-1 text-slate-500 hover:text-rose-400 group-hover:block"><LucideIcons.Trash2 className="h-3 w-3" /></button>}</article>; })}<button onClick={() => setTab('triggers')} className="flex w-52 items-center justify-center gap-2 rounded-xl border border-dashed border-primary-500/50 bg-primary-500/5 p-3 text-[10px] font-semibold text-primary-300 hover:bg-primary-500/10"><LucideIcons.Plus className="h-4 w-4" />Add new trigger</button></div>
        <div className="relative h-14 w-full max-w-[900px]"><div className="absolute left-1/2 top-0 h-full w-px bg-slate-700" /><div className="absolute left-[8%] right-[8%] top-7 h-px bg-slate-700" /><span className="absolute left-1/2 top-5 -translate-x-1/2 rounded-full border border-border bg-surface p-1 text-slate-500"><LucideIcons.Plus className="h-3 w-3" /></span></div>
        {steps.map((step: any, index: number) => { const catalogItem = ACTION_CATALOG.flatMap((group) => group.items).find((item) => item.id === step.actionType || (item.runtimeType === step.actionType && item.config?.provider === step.config?.provider)); const Icon = iconFor(catalogItem?.icon || 'Zap'); return <React.Fragment key={step.id || `${step.actionType}-${index}`}><div onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const raw = event.dataTransfer.getData('automation/catalog-item'); if (raw) insertItem(JSON.parse(raw), index); else if (dragIndex !== null) reorder(dragIndex, index); }} className="group flex h-12 w-80 items-center justify-center"><div className="h-full w-px bg-slate-700" /><span className="absolute hidden rounded-full border border-primary-500/40 bg-primary-600 p-1 text-white group-hover:block"><LucideIcons.Plus className="h-3 w-3" /></span></div><article draggable onDragStart={(event) => { setDragIndex(index); event.dataTransfer.effectAllowed = 'move'; }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (dragIndex !== null && dragIndex !== index) reorder(dragIndex, index); }} onClick={() => setSelectedIndex(index)} className={`group w-80 cursor-pointer rounded-xl border bg-surface-card p-4 shadow-[0_12px_35px_rgba(0,0,0,.3)] transition ${selectedIndex === index ? 'border-primary-400 ring-2 ring-primary-500/15' : 'border-border hover:border-slate-600'}`}><div className="flex items-start gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border ${colorClasses[catalogItem?.color || 'slate']}`}><Icon className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-bold uppercase tracking-wider text-slate-500">Action {index + 1}</span><LucideIcons.GripVertical className="h-3.5 w-3.5 text-slate-600" /></div><div className="mt-1 truncate text-xs font-bold text-white">{step.name}</div><div className="mt-1 truncate text-[9px] text-slate-500">{catalogItem?.description || step.actionType.replaceAll('_', ' ')}</div></div></div></article></React.Fragment>; })}
        <div onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const raw = event.dataTransfer.getData('automation/catalog-item'); if (raw) insertItem(JSON.parse(raw)); else if (dragIndex !== null) reorder(dragIndex, steps.length - 1); }} className="flex h-12 items-center justify-center"><div className="h-full w-px bg-slate-700" /></div><button onClick={() => setTab('actions')} className="flex items-center gap-2 rounded-lg border border-dashed border-primary-500/50 bg-primary-500/5 px-4 py-2 text-[10px] font-semibold text-primary-300 hover:bg-primary-500/10"><LucideIcons.Plus className="h-3.5 w-3.5" />Add action</button>
      </div>
    </main>
    <aside className="border-l border-border bg-surface-card">{selectedIndex === null ? <div className="flex h-full flex-col items-center justify-center p-8 text-center"><LucideIcons.MousePointerClick className="h-8 w-8 text-slate-700" /><h3 className="mt-3 text-xs font-bold text-slate-300">Select an action</h3><p className="mt-1 text-[10px] leading-relaxed text-slate-500">Click a node to configure it. Drag actions from the library into any connector.</p></div> : <div className="flex h-full flex-col"><div className="border-b border-border p-4"><div className="flex items-center justify-between"><div><div className="text-[9px] font-bold uppercase tracking-wider text-primary-400">Action settings</div><div className="mt-1 text-sm font-bold text-white">{steps[selectedIndex]?.name}</div></div><button onClick={() => setSelectedIndex(null)} className="text-slate-500"><LucideIcons.X className="h-4 w-4" /></button></div></div><div className="flex-1 space-y-4 overflow-y-auto p-4 text-[10px]"><label className="block"><span className="mb-1.5 block font-semibold text-slate-400">Action name</span><input value={steps[selectedIndex]?.name || ''} onChange={(event) => updateSelected({ name: event.target.value })} className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-xs text-white outline-none focus:border-primary-500" /></label><label className="block"><span className="mb-1.5 block font-semibold text-slate-400">Configuration (JSON)</span><textarea key={`${selectedIndex}-${JSON.stringify(steps[selectedIndex]?.config)}`} defaultValue={JSON.stringify(steps[selectedIndex]?.config || {}, null, 2)} onBlur={(event) => { try { updateSelected({ config: JSON.parse(event.target.value) }); } catch { event.target.value = JSON.stringify(steps[selectedIndex]?.config || {}, null, 2); } }} rows={12} className="w-full rounded-lg border border-border bg-surface px-3 py-2 font-mono text-[10px] leading-relaxed text-slate-300 outline-none focus:border-primary-500" /></label><button onClick={() => { const next = normalize(steps.filter((_: any, index: number) => index !== selectedIndex)); setSelectedIndex(null); void onChangeSteps(next); }} disabled={steps.length <= 1} className="flex w-full items-center justify-center gap-2 rounded-lg border border-rose-500/20 bg-rose-500/5 px-3 py-2 text-rose-400 disabled:opacity-30"><LucideIcons.Trash2 className="h-3.5 w-3.5" />Delete action</button></div></div>}</aside>
  </div>;
}
